### ISSUE TITLE
The code is not working as expected as told by the README.  What should I do?

### ISSUE THREAD

**Issue by shyamalschandra** [Ghadjeres/DeepBach#10]
Input:

`python3 deepBach.py --dataset /Users/shyamalsuhanachandra/websites/MIDI\ Repository/www.piano-midi.de/midis/chopin/ --ext dowland -t 30 --timesteps 32 -u 256 256 -d 256 -b 32
`
Output:
```
Creating dataset
Warning: SLUR_SYMBOL used in standard_note
Warning: SLUR_SYMBOL used in standard_note
Warning: SLUR_SYMBOL used in standard_note
Warning: SLUR_SYMBOL used in standard_note
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "deepBach.py", line 847, in <module>
    main()
  File "deepBach.py", line 775, in main
    voice_ids=[0, 1, 2, 3])
  File "/Users/shyamalsuhanachandra/DeepBach/data_utils.py", line 582, in initialization
    metadatas=metadatas)
  File "/Users/shyamalsuhanachandra/DeepBach/data_utils.py", line 247, in make_dataset
    pickle.dump(dataset, open(dataset_name, 'wb'), pickle.HIGHEST_PROTOCOL)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/custom_dataset/.pickle'
```

What should I do?

**Comment by Ghadjeres** [comment]
Hi,
Try removing the last '/' when specifying your dataset folder.
`
python3 deepBach.py --dataset /Users/shyamalsuhanachandra/websites/MIDI\ Repository/www.piano-midi.de/midis/chopin --ext chopin -t 30 --timesteps 32 -u 256 256 -d 256 -b 32
`
should work

**Comment by shyamalschandra** [comment]
I don't understand why I would need to remove the last '/' from my dataset folder.  That is the folder of the MIDIs.

**Comment by Ghadjeres** [comment]
Because of these lines
```
    # datasets
    # set pickled_dataset argument
    if args.dataset:
        dataset_path = args.dataset
        dataset_name = dataset_path.split('/')[-1]
        pickled_dataset = 'datasets/custom_dataset/' + dataset_name + '.pickle'
```

**Comment by bzamecnik** [comment]
Better use `os.path.join()` to avoid this kind of problems:

```
import os.path
pickled_dataset = os.path.join('datasets/custom_dataset/', dataset_name + '.pickle')
```

**Comment by KKONZ** [comment]
I am attempting to create a custom dataset model based off of BMW 3.6 - 5.7 to start and I keep getting an error for line 365 chorale_index = np.random(choice(chorale_indices).  
ValueError: a must be non-empty 

Not passing an -- dataset argument works fine, but when I attempt to create a custom file a pickle file is created in the custom_dataset folder but does not contain any data. 

I am running the code on a Windows machine, could that be the source of the issue?

**Comment by bzamecnik** [comment]
@KKONZ I get the same error. The thing is that from the directory of MIDI file, only one was used and the training split size from dataset of size 1 was rounded to 0.

**Comment by bzamecnik** [comment]
Actually the `dataset_name` is calculated in not too robust way due to `dataset_path.split('/')[-1]`.
