### ISSUE TITLE
What  do  the    X,  X_metadatas  and   metadatas  mean?

### ISSUE THREAD

**Issue by handsomeyewenhao** [Ghadjeres/DeepBach#15]

**Comment by Ghadjeres** [comment]
Classes that inherits from the Metadata class allow to compute additional information about chorales such as the current key, information about the current beat etc. .
These are stored in the metadatas list.
X is the dataset of all chorales (a list of arrays)
and X_metadatas the list of all metadata, one for each chorale in X.
