### ISSUE TITLE
making pickle file from new midi files

### ISSUE THREAD

**Issue by shinandrew** [Ghadjeres/DeepBach#2]
Thanx for the great repository.

I'd like to examine DeepBach with my own MIDI dataset,
but the way pickle file is made is a bit difficult to comprehend.

Could you please let us know as to how to convert MIDI files to the pickle file to be used,
e.g. what kind of preprocessing is needed, how to organize them, etc?

Thanx a bunch.

**Comment by Ghadjeres** [comment]
See the --dataset argument  #8 
Your dataset folder must contains all your midi files.
The midi files must be multitrack, each track being monophonic. You need to be able to parse them using the converter.parse function from music21
Thanks
