### ISSUE TITLE
models_zoo.py:deepBach has not been updated for Keras 2

### ISSUE THREAD

**Issue by bzamecnik** [Ghadjeres/DeepBach#22]
In b8f6049 and other commits there the model code for upgraded for compatibility with Keras 2. However in this commit some necessary changes are missing, in particular the `merge()` function was replaced by `add()` or `concatenate()` only in the `deepbach_skip_connections` model, but not in `deepBach`. This results in the first example command in README to fail.

**Comment by Ghadjeres** [comment]
You are right. Thanks!
