### ISSUE TITLE
DeepBach access rights issue

### ISSUE THREAD

**Issue by Aerny** [Ghadjeres/DeepBach#45]
This command seems to link to a non existing page:

_git clone git@github.com:SonyCSL-Paris/DeepBach.git
cd DeepBach
conda env create -f environment.yml_

When I use it I get this message:

_Last login: Fri Feb 23 10:11:20 on console
mac-pro-van-arnold-veeman:~ arnoldveeman$ git clone git@github.com:SonyCSL-Paris/DeepBach.git
Cloning into 'DeepBach'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
mac-pro-van-arnold-veeman:~ arnoldveeman$ cd DeepBach
-bash: cd: DeepBach: No such file or directory
mac-pro-van-arnold-veeman:~ arnoldveeman$ conda env create -f environment.yml_

Can someone help me out in a comprehensive way?

Thank you

**Comment by hans-ekbrand** [comment]
This is not a bug in DeepBach.

The command you used works fine, if you have ssh-access to github, which you can get for free by registering an account and upload you public key. You can clone DeepBach without ssh-access to github, just use:

`git clone https://github.com/Ghadjeres/DeepBach.git`

**Comment by Aerny** [comment]
I new to this, but I am going to try it out today! Thanks for the tip!
