### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by MarcVilanova** [Ghadjeres/DeepBach#46]
Hi all! 

I have a small budget if someone can help me to install the DeepBach plugin via TeamViewer or something like this. I tried myself, first time in github, first time opening terminal and I 
have been able to install Music21 and other things but it's not really for users so finally I'll need some help...

Please write me if you can help, I would love to experiment with DeepBach. My email: marcvilanovapinyol@gmail.com

Thanks!

**Comment by Ghadjeres** [comment]
I'm eager to see the results!
Best
