### ISSUE TITLE
I do not work flask

### ISSUE THREAD

**Issue by Peri2** [Ghadjeres/DeepBach#48]
Hello
I'm not a programmer, I'm a musician. I want my students to analyze some compositions made by deepbach. t first I did not function Deepbach, but when I tried the deepbach of Sony CSL Paris, it worked great.
It took me a while for deepbach to do something. At least I got him to work searching for extra information on the internet. It is not easy. Everything I have done since Anaconda.

But what I have not gotten is that it functions plugin for Musescore. I install flask from anaconda, I import it 
from python. Since I use windows 8.1 (i5, x64), I discovered later that "export" does not work on windows, I used "set" instead. So I put this:

(tensorflow) C: \ Users \ Boss \ DeepBach> set FLASK_APP = plugin_flask_server.py

(tensorflow) C: \ Users \ Boss \ DeepBach> flask run
 * Serving Flask app "plugin_flask_server.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a WSGI server production instead.
 * Debug mode: off
music21: Certain music21 functions might need the optional package matplotlib;
                  If you run into errors, install it by following the instructionsns at
                  http://mit.edu/music21/doc/installing/installAdditional.html
Using Theano backend.
WARNING (theano.configdefaults): g ++ not available, if using conda: `conda install m2w64-toolchain
C: \ ProgramData \ Anaconda3 \ envs \ tensorflow \ lib \ site-packages \ theano \ configdefaults
.py: 560: UserWarning: DeprecationWarning: there is no c ++ compiler.This is deprecated and with Theano 0.11 a c ++ compiler will be mandatory  warnings.warn ("DeprecationWarning: there is no c ++ compiler."
WARNING (theano.configdefaults): g ++ not detected! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: N
or module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions
Usage: flask run [OPTIONS]

Error: While importing "DeepBach.plugin_flask_server", an ImportError was raised
:
Traceback (most recent call last):
  File "C: \ ProgramData \ Anaconda3 \ envs \ tensorflow \ lib \ site-packages \ flask \ cli.py"
, line 235, in locate_app
    __import __ (module_name)
  File "C: \ Users \ Boss \ DeepBach \ plugin_flask_server.py", line 13, in <module>
    from DeepBach.model_manager import load_models
  File "C: \ Users \ Boss \ DeepBach \ model_manager.py", line 13, in <module>
    from .data_utils import generator_from_raw_dataset, BACH_DATASET, \
ImportError: can not import name 'PACKAGE_DIR'

If I try to use the plugin, it does not work. I do not know what I will be doing wrong.

Neither I work the configuration that puts music21. I had to configure it in another way:
python -m music21.configure

I have observed that the value -l is increased from 600 to 1000, the result is dissonant. It gives good results 
between 400 and 200, but the length in bars is smaller.
I have also tried to harmonize a melody, but the result is other than expected, it harmonizes it in a minor tone..

Greetings and congratulations for deepbach

**Comment by Ghadjeres** [comment]
Hi,
Thanks for your interest and congrats to have gone through all these steps. I'm currently working to make DeepBach targeted to musicians. It'll be available soon.
Concerning your last observations, this is normal. If you increase the length of your chorale, you also have to increase the amount of "time" (number of iterations) you need to compose it.
And for the unexpected reharmonization, I think that it's nice to were surprised. (It is possible to control whether you want to reharmonize in major or in minor. It is just that I prefered no to have this feature  in the pretrained model __ in can be too restrictive __)
