### ISSUE TITLE
AttributeError: module 'music21.corpus' has no attribute 'getBachChorales'

### ISSUE THREAD

**Issue by meumesmo** [Ghadjeres/DeepBach#53]
Hello!
I'm trying to use the command:
python3 deepBach.py -l 100

and I'm getting the error
AttributeError: module 'music21.corpus' has no attribute 'getBachChorales'

**Comment by Philogag** [comment]
I meet this problem as well

**Comment by Ghadjeres** [comment]
It's because music21 has been updated since then.
I just pushed a Pytorch version which uses an up-to-date version of music21. You should no longer have these issues.
