### ISSUE TITLE
Ubuntu problems with data setup

### ISSUE THREAD

**Issue by TuulaP** [Ghadjeres/DeepBach#58]
Interesting module, the basic setup is causing me some problems. In ubuntu:

```
conda env create --name deepbach_pytorch -f environment.yml

SpecNotFound: Invalid name, try the format: user/package
```
And if I skip that, then 

the next examples, e.g. 

```
python3 deepBach.py
Using TensorFlow backend.
ends up to:
  File "/mnt/c/dev/2019/DeepBach/data_utils.py", line 584, in initialization
    chorale_list = filter_file_list(corpus.getBachChorales(fileExtensions='xml'))
AttributeError: module 'music21.corpus' has no attribute 'getBachChorales'

```

so some data seems to be missing, and wondering where I could get those.

**Comment by Ghadjeres** [comment]
Hi!
Are you on the master branch?
Because, this error is due to the fact that you do not have the latest version of music21

**Comment by soma-n8** [comment]
Here has same problem,
But my music21 is 5.7.0
when I try to update it
I input this:

pip install --upgrade music21

and I got This:
Requirement already up-to-date: music21 in /home/mors/anaconda3/lib/python3.6/site-packages (5.7.0)

**Comment by soma-n8** [comment]
BTW
I tried this:
pip uninstall music21
pip install --upgrade music21

It's work.
