### ISSUE TITLE
Problems with harmonising supplied soprano melody

### ISSUE THREAD

**Issue by rzil** [Ghadjeres/DeepBach#6]
Following instructions in the Readme file I tried the command
`python3 deepBach.py -m melody1.mid -p -i 10000`
with the attached midi file. The results were garbage: totally dissonant. I take it there is something wrong with either a) the settings I used or b) the midi file. Some help here would be appreciated.

[melody1.mid.zip](https://github.com/SonyCSL-Paris/DeepBach/files/696826/melody1.mid.zip)

**Comment by Ghadjeres** [comment]
Have you trained the model (the -t option?)
You may add more iterations too

**Comment by timokeller** [comment]
I have a similar problem: First, I did python deepBach.py for training, but the created chorale is also totally dissonant.

**Comment by Ghadjeres** [comment]
There is a new implementation in Pytorch (on master). Maybe you will have more chance with this one!
