### ISSUE TITLE
Code not implementing

### ISSUE THREAD

**Issue by Newtonsnipps** [Ghadjeres/DeepBach#86]
Hello, 
I've been trying to run and implement the programme. Its already been a few days and it has been impossible. Is there any step by step guide to do so?

**Comment by cmaxreilly** [comment]
Hello! I am new here, but I am also having some problems with the README. Have you consulted that? If so, what specific problems have you had?

**Comment by Ghadjeres** [comment]
I just fixed the repo address in the Installation section.
There was indeed an error there.
Thanks!
