### ISSUE TITLE
Installation section deprecated

### ISSUE THREAD

**Issue by cmaxreilly** [Ghadjeres/DeepBach#87]
It appears that the command `git clone git@github.com:SonyCSL-Paris/DeepBach.git` no longer works because SonyCSL is not hosting the repository, at least as of this writing. Has anyone else experienced this issue?

**Comment by Ghadjeres** [comment]
Thanks for pointing this out.
The correct address is indeed `git clone git@github.com:Ghadjeres/DeepBach.git`.
